spring:
  datasource:
    username: root
    password: 111
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huaibei?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://67.216.193.93:3306/huaibei?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell


wechat:
  mpAppId: wxce7938b3fc2f0481
  mpAppSecret: b18eb1d06c87cd9f32c53bec312a8820
  mchId: xxx
  mchKey: xxx
  keyPath: xxx
  notifyUrl: http://c17724517a2f4531.natapp.cc/pay/notify


