spring:
  datasource:
    username: root
    password: toor
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://67.216.193.93:3306/huaibei?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true