spring:
  datasource:
    username: root
    password: 111
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huaibei?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://67.216.193.93:3306/huaibei?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
server:
  context-path: /sell

